---
title: "Player 2 vs 3 point comparison"
author: "Chris Bryden"
date: "6/13/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(reshape2)
library(readr)
```


```{r}
playerData <- read_csv("D:/MyShinyApp/nba2or3_2021_player_stats.csv")
#View(playerData)


row <- subset(playerData, playerName == "Kevin Durant")
#View(row)
player2PtMake <- row
player3PtMake <- row[,3]

player2PtMake
### to import data, just download the attatched excel file, and place the location in the read_csv in line 20.
```



#### Generic Player Comparison Function

```{r}
player_2_vs_3_comparison <- function(player_name, number_of_simulated_shot_attempts){

# Read in the Data we will be using
playerData <- read_csv("C:/Users/Christopher/Downloads/Stat 327/Final Project/2or3/nba2or3_2021_player_stats.csv")
#View(playerData)

# We create 2 shot objects, for a 2 point shot attempt, and a 3 point shot attempt.
# If a player makes the shot, they will get 2 or 3 points based on what shot was attempted
# If a player misses, they will receive 0
shot2 <- c(2, 0)
shot3 <- c(3, 0)

# We use the DPLYR package and the FILTER function to go through the playerName column of our dataset, and when it finds the match, it filters that row. From there we use the corresponding column index to specify the statistic we need. 

selectedPlayer <- filter(playerData, playerName == player_name)
player2PtMake <- selectedPlayer[,2]
player2PtMiss <- selectedPlayer[,3]
player3PtMake <- selectedPlayer[,4]
player3PtMiss <- selectedPlayer[,5]


# 

player2_prob <- c(player2PtMake, player2PtMiss)
player3_prob <- c(player3PtMake, player3PtMiss)

# Saves users simulated shot attempts as a variable we will use later
number_of_simulated_shot_attempts <- number_of_simulated_shot_attempts


player2samp <- sample(shot2,
                      size = number_of_simulated_shot_attempts, 
                      replace = TRUE, 
                      prob = player2_prob)

player3samp <- sample(shot3,
                      size = number_of_simulated_shot_attempts,
                      replace = TRUE,
                      prob = player3_prob)

player2cumulative <- cumsum(player2samp)
player3cumulative <- cumsum(player3samp)

#player2cumulative
#player3cumulative

simulated_shot_attempts <- seq(1, number_of_simulated_shot_attempts, by = 1)

player2MaxPoints <- max(player2cumulative)
player3MaxPoints <- max(player3cumulative)

player2PointsPerShot <- max(player2cumulative)/number_of_simulated_shot_attempts
player3PointsPerShot <-max(player3cumulative) / number_of_simulated_shot_attempts

player_df <- data.frame(simulated_shot_attempts, player2cumulative, player3cumulative)
player_df

player_plot <- ggplot()+
  geom_line(data = player_df, aes(x = simulated_shot_attempts, 
                              y = player2cumulative,
                              col = "2 Point Shot Attempt")) +
  geom_line(data = player_df, aes(x = simulated_shot_attempts,
                              y = player3cumulative,
                              col = "3 Point Shot Attempt")) +
  labs(title = paste("2 v. 3 Comparison For", selectedPlayer),
       subtitle = "By 2020-21 Shooting Percentages",
       y = "Simulated Points Scored",
       x = "Simulated Shot Attempts",
       color = "Shot Type") +
  theme_minimal()

player_plot

}


```

```{r}
player_2_vs_3_comparison("Kevin Durant", 20)
player_2_vs_3_comparison("LeBron James", 20)
player_2_vs_3_comparison("Stephen Curry", 20)
player_2_vs_3_comparison("Saddiq Bey", 20)
player_2_vs_3_comparison("Damian Lillard", 20)
player_2_vs_3_comparison("Trae Young", 20)
player_2_vs_3_comparison("Luka Doncic", 20)
player_2_vs_3_comparison("Kyrie Irving", 20)
player_2_vs_3_comparison("James Harden", 20)
player_2_vs_3_comparison("LaMelo Ball", 20)
```

```{r}
player_2_vs_3_comparison("Kevin Durant", 81)
player_2_vs_3_comparison("LeBron James", 81)
player_2_vs_3_comparison("Stephen Curry", 81)
player_2_vs_3_comparison("Saddiq Bey", 81)
player_2_vs_3_comparison("Damian Lillard", 81)
player_2_vs_3_comparison("Trae Young", 81)
player_2_vs_3_comparison("Luka Doncic", 81)
player_2_vs_3_comparison("Kyrie Irving", 81)
player_2_vs_3_comparison("James Harden", 81)
player_2_vs_3_comparison("LaMelo Ball", 81)
```

```{r}
player_2_vs_3_comparison("Kevin Durant", 1558)
player_2_vs_3_comparison("LeBron James", 1558)
player_2_vs_3_comparison("Stephen Curry", 1558)
player_2_vs_3_comparison("Saddiq Bey", 1558)
player_2_vs_3_comparison("Damian Lillard", 1558)
player_2_vs_3_comparison("Trae Young", 1558)
player_2_vs_3_comparison("Luka Doncic", 1558)
player_2_vs_3_comparison("Kyrie Irving", 1558)
player_2_vs_3_comparison("James Harden", 1558)
player_2_vs_3_comparison("LaMelo Ball", 1558)
```

```{r}
player_2_vs_3_comparison("Kevin Durant", 28307)
player_2_vs_3_comparison("LeBron James", 28307)
player_2_vs_3_comparison("Stephen Curry", 28307)
player_2_vs_3_comparison("Saddiq Bey", 28307)
player_2_vs_3_comparison("Damian Lillard", 28307)
player_2_vs_3_comparison("Trae Young", 28307)
player_2_vs_3_comparison("Luka Doncic", 28307)
player_2_vs_3_comparison("Kyrie Irving", 28307)
player_2_vs_3_comparison("James Harden", 28307)
player_2_vs_3_comparison("LaMelo Ball", 28307)
```


